#----------------------------------------------------------------------------------------------------#
#------- 1. 此配置文件作为默认全面的配置信息文件，包含了本服务最全的配置信息，供开发或运维人员参考配置；-------- #
#------- 2. 不建议直接修改此配置文件，而是复制相关配置项到 application-local.yml 中去修改；---------------- #
#------- 3. application-local.yml 配置文件中的配置优先级比 application.yml 配置文件要高；---------------- #
#------- 4. 运维人员需要注意的是，配置项的冒号(':')后面需要有一个空格，否则配置不会生效。-------------------- #
#----------------------------------------------------------------------------------------------------#

spring:
  profiles:
    active: local
  application:
    name: gitlab-release-server

# 服务端口，将默认为5050.
server:
  port: 5050

# 日志相关的简单配置.
logging:
  file: logs/gitlab-release-server.log
  level:
    root: info
    org:
      apache: warn
      springframework: warn

# 本系统的相关配置项.
system:
  baseUrl: http://127.0.0.1:5050
  # Minio的配置，这是一个用于开发测试的 minio 地址.
  minio:
    endpoint: http://172.25.16.76:9000
    accessKey: dev
    secretKey: 123456789
    bucket: releases
